#!/bin/bash

# Time
for i in size*.pl ; do echo $i ; time perl $i   ; done 

# Peak Mem usage
for i in size*.pl ; do echo $i ; ( memusg perl $i )  ; done 

# Ending mem usage
for i in size*.pl ; do echo $i ; ( perl $i wait & ) ; done 
sleep 10 
ps axv | grep -P "^\s*PID|[s]ize-"

# Exif
for i in test*.jpg ; do exiftool $i | sort > "${i%.jpg}.exif" ; done

echo "ready to see exif diffs?"
read y

for i in test-*.exif ; do 
	echo $i
	diff test.exif $i | more

	echo "That was $i. Next?"
	read y
done

